### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by kopax** [foxel/seafile-docker#1]
@foxel I would be happy to have a try now,

Could you add some more details : 

eg  :
- data persistence volumes
- how to perform safe backup
- how to perform safe restore
- how to perform safe upgrade

These are **core** features and **cannot** be ignored or untested.

**Comment by foxel** [comment]
@kopax 

Container uses named persistent volumes.
For backup and restore routines please see http://manual.seafile.com/maintain/backup_recovery.html and https://docs.docker.com/engine/tutorials/dockervolumes/#/backup-restore-or-migrate-data-volumes

Upgrade instructions rely on seafile general update instructions. And if this docker container will require any extra action information will be added as new versions are added.
