### ISSUE TITLE
configuration for nginx reverse-proxy

### ISSUE THREAD

**Issue by capsudo** [foxel/seafile-docker#3]
Hi, first thanks for your this project, it is much better than the official seafile docker.

I am using a nginx reverse-proxy docker container to redirect to other docker containers (it eases HTTPS and port mapping) as described here : https://blog.linuxserver.io/2017/11/28/how-to-setup-a-reverse-proxy-with-letsencrypt-ssl-for-all-your-docker-apps/

One of the containers being of course foxel/seafile (seafile container itself embedding a nginx reverse-proxy server to its seahub and seafile servers visible here : https://github.com/foxel/seafile-docker/blob/master/etc/nginx/sites-available/seafile.conf).

I use the env var `- "SEAFILE_URL=https://domain.com/seafile"` and I tried several things for the nginx conf :

```
location /seafile/ {
		proxy_pass http://seafile;
		rewrite ^/grafana/(.*) /$1 break;
		proxy_set_header   Host $host;
}
```

```
location /seafile {
		proxy_pass http://seafile;
		include /config/nginx/proxy.conf;  
}
```

```
location /seafile {
		proxy_pass http://seafile;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

```

```
location /seafile {
		proxy_pass http://seafile;
		proxy_bind $server_addr;
		proxy_set_header X-Forwarded-Host $server_name;
		proxy_set_header X-Forwarded-Ssl     on;
		include /config/nginx/proxy.conf;  
} 
```

```
location /seafile {
		proxy_pass http://seafile/seafile;
		include /config/nginx/proxy.conf;  
}
```

```
location /seafile {
		proxy_pass http://seafile/seafile;
		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
		proxy_redirect off;
		proxy_buffering off;
		proxy_set_header        Host            $host;
		proxy_set_header        X-Real-IP       $remote_addr;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

```
location /seafile {
	proxy_pass http://seafile;
	proxy_read_timeout 310s;
	proxy_set_header Host $host;
	proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header Connection "";
	proxy_http_version 1.1;
}

```

*Note : http://seafile is resolved via docker own DNS system, `seafile`o being the name of the container declared in `docker-compose.yml`, I launch the reverse-proxy and the seafile container on the same network using  `networks:  lets-encrypt-docker_nginx-net`*

The only configuration that seemed to work, but only for setup (`docker-compose exec seafile setup`) is the following (from https://forum.seafile.com/t/solved-using-nginx-reverse-proxy-for-seafile-docker/6109/8) :

```
location /seafile {
	proxy_pass http://seafile;
	proxy_read_timeout 310s;
	proxy_set_header Host $host;
	proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header Connection "";
	proxy_http_version 1.1;
}
```

However seafile is still not working at https://mydomain.com/seafile (it shows a seafile error webpage stating "Sorry, but the requested page could not be found." with different languages).

Could you help me on that ?

**Comment by capsudo** [comment]
Ok I managed to fix it, the seafile block in main nginx conf files was correct (`location /seafile { ... }`), but few other settings had to be set for seafile to work at non-root domain (https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html).

- `SEAFILE_URL` should be set to `https://domain.com/seafile`

- `settings_seahub.py` had to be modified with following settings :

```
SERVE_STATIC = False
MEDIA_URL = '/seafile/seafmedia/'
COMPRESS_URL = MEDIA_URL
STATIC_URL = MEDIA_URL + 'assets/'
SITE_ROOT = '/seafile/'
LOGIN_URL = '/seafile/accounts/login/'
```
- seafile internal nginx config `seafile.conf` must be modified also :

```
location / {
		...
		fastcgi_param   HTTPS               on;
		fastcgi_param   HTTP_SCHEME         https;
		...
}

...

location /seafile/seafmedia {
		rewrite ^/seafile/seafmedia(.*)$ /media$1 break;
		root /opt/seafile/latest/seahub;
}
```

Full details available here : https://monkeydri.github.io/posts/seafile-https-nginx-reverse-proxy/

**Comment by foxel** [comment]
Thanks. This is a useful piece of code.
