### ISSUE TITLE
cannot run fsck inside docker

### ISSUE THREAD

**Issue by capsudo** [foxel/seafile-docker#8]
`docker compose exec -it seafile bash`
`cd /opt/seafile/6.3.3/`
`./seaf-fsck.sh --export some-library-id /seafile/export/`

seaf-fsck.c(156): Current user (0) is not the user for running seafile server (999). Unable to run fsck.

Trying to use seafile user (999) does not seem possible : `su - seafile` logs back to root.

---
seafile image 6.3.3

**Comment by foxel** [comment]
Hi.

seafile user has no shell assigned, so you should set `-s` parameter for `su`

Also added script wrapper for FSCK the same way it's done for GC.

**Comment by capsudo** [comment]
Thanks @foxel it worked great `su -s /bin/sh seafile` then `seaf-fsck` (just had to `chown -R seafile:seafile` my external drive before switching to seafile user).
